inc:
  # Blog Information
  title:        "Lovell Felix"
  blog_title: "Blog"
  blog_subtitle:     "Routine Tutorials"
  cover_image:  blog-cover.png
  logo:         logo.png
  blog_link: /blog/

  # Company information
  company:      Lovell Felix
  landing_page_title: "Geek, Google Fanboy, Tech News Junkie, Entrepreneur - Drinker of tea :)"
  url:          http://lovellfelix.com/
  facebook:     lovell.felix
  twitter:      lovellfelix
  gplus:        '102676824509364241023'
  profile_pic: https://lh3.googleusercontent.com/-Ubq3pEfgeLk/AAAAAAAAAAI/AAAAAAAAOvs/nGutWDQ5OGc/s120-c/photo.jpg.png
  about_link:   /about/

  #Resume
  resume_title: "Lovell Felix - Resume"
  #resume_link: /resume/
  resume_link: http://www.linkedin.com/in/lovellfelix

  # Labs Information
  labs_title: Labs
  labs_subtitle: Playground For Some Of My Wild And Crazy Ideas :)
  labs_cover_image:  lab-cover.jpg
  labs_link: /labs/
  tagline:      " "

  # Testimonials
  testimonials_title: Testimonials
  testimonials_subtitle: What people are saying
  testimonials_cover_image:  testimonials-cover.jpg
  testimonials_link: /testimonials/


  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google:
      # eg. 'UA-123-12'
      id:       UA-18508266-1


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'PT+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

collections:
  labs:
    output: true
    permalink: /labs/:path/

url:         http://lovellfelix.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [Gemfile, Gemfile.lock, Rakefile, bk, psd, screenshots]


# Show future posts
future:      false
show_drafts: nil
limit_posts: 0

highlighter: pygments

relative_permalinks: true
permalink: /blog/:title/
paginate_path: '/blog/page:num'
paginate: 5


excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _assets/stylesheets
  style:            :compressed

